### ISSUE TITLE
Boxen broken under macOS Sierra

### ISSUE THREAD

**Issue by julienlavergne** [boxen/boxen#205]
Hello guys.

Boxen seems to be broken under macOS Sierra.

Have you experimented a successful boxen install running under macOS Sierra ?

Thx

**Comment by jacobbednarz** [comment]
Are you able to provide the output or problem you are seeing?

**Comment by julienlavergne** [comment]
I obtained this output:

```
julien@Carbonite:/opt/boxen$ boxen
--> Preparing to auto-update...
--> Complete! Nothing new from upstream.
Notice: Compiled catalog for pc20.home in environment production in 2.80 seconds
Notice: Package[boxen/brews/hub](provider=homebrew): Updating homebrew formulas
Error: Could not update: Execution of 'brew boxen-install boxen/brews/hub' returned 1: Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/opt/boxen/homebrew/Library/Taps/boxen/homebrew-brews/hub.rb:6:in `<class:Hub>'
Please report this to the boxen/brews tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/opt/boxen/homebrew/Library/Taps/boxen/homebrew-brews/hub.rb:6:in `<class:Hub>'
Please report this to the boxen/brews tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/opt/boxen/homebrew/Library/Taps/boxen/homebrew-brews/hub.rb:6:in `<class:Hub>'
Please report this to the boxen/brews tap!

Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
==> Installing hub from boxen/brews
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/opt/boxen/homebrew/Library/Taps/boxen/homebrew-brews/hub.rb:6:in `<class:Hub>'
Please report this to the boxen/brews tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/opt/boxen/homebrew/Library/Taps/boxen/homebrew-brews/hub.rb:6:in `<class:Hub>'
Please report this to the boxen/brews tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/opt/boxen/homebrew/Library/Taps/boxen/homebrew-brews/hub.rb:6:in `<class:Hub>'
Please report this to the boxen/brews tap!

==> Downloading https://github.com/github/hub/archive/v2.2.1.tar.gz
Already downloaded: /opt/boxen/cache/homebrew/hub-2.2.1.tar.gz
Warning: Calling Pathname#sha1 is deprecated!
Use Pathname#sha256 instead.
/opt/boxen/homebrew/Library/Homebrew/extend/pathname.rb:320:in `verify_checksum'

==> script/build
Last 15 lines from /Users/julien/Library/Logs/Homebrew/hub/01.build:
2016-08-22 21:49:10 +0200

script/build

# _/private/tmp/hub-20160822-51203-y0p5wo/hub-2.2.1
/opt/boxen/homebrew/Cellar/go/1.7/libexec/pkg/tool/darwin_amd64/link: -X flag requires argument of the form importpath.name=value

READ THIS: https://git.io/brew-troubleshooting

/opt/boxen/homebrew/Library/Homebrew/utils/github.rb:212:in `raise_api_error': Validation Failed (GitHub::Error)
       	from /opt/boxen/homebrew/Library/Homebrew/utils/github.rb:174:in `open'
       	from /opt/boxen/homebrew/Library/Homebrew/utils/github.rb:219:in `issues_matching'
       	from /opt/boxen/homebrew/Library/Homebrew/utils/github.rb:252:in `issues_for_formula'
       	from /opt/boxen/homebrew/Library/Homebrew/exceptions.rb:312:in `fetch_issues'
       	from /opt/boxen/homebrew/Library/Homebrew/exceptions.rb:308:in `issues'
       	from /opt/boxen/homebrew/Library/Homebrew/exceptions.rb:353:in `dump'
       	from /opt/boxen/homebrew/Library/Homebrew/brew.rb:126:in `rescue in <main>'
       	from /opt/boxen/homebrew/Library/Homebrew/brew.rb:26:in `<main>'
Wrapped exception:
Execution of 'brew boxen-install boxen/brews/hub' returned 1: Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/opt/boxen/homebrew/Library/Taps/boxen/homebrew-brews/hub.rb:6:in `<class:Hub>'
Please report this to the boxen/brews tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/opt/boxen/homebrew/Library/Taps/boxen/homebrew-brews/hub.rb:6:in `<class:Hub>'
Please report this to the boxen/brews tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/opt/boxen/homebrew/Library/Taps/boxen/homebrew-brews/hub.rb:6:in `<class:Hub>'
Please report this to the boxen/brews tap!

Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
==> Installing hub from boxen/brews
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/opt/boxen/homebrew/Library/Taps/boxen/homebrew-brews/hub.rb:6:in `<class:Hub>'
Please report this to the boxen/brews tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/opt/boxen/homebrew/Library/Taps/boxen/homebrew-brews/hub.rb:6:in `<class:Hub>'
Please report this to the boxen/brews tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/opt/boxen/homebrew/Library/Taps/boxen/homebrew-brews/hub.rb:6:in `<class:Hub>'
Please report this to the boxen/brews tap!

==> Downloading https://github.com/github/hub/archive/v2.2.1.tar.gz
Already downloaded: /opt/boxen/cache/homebrew/hub-2.2.1.tar.gz
Warning: Calling Pathname#sha1 is deprecated!
Use Pathname#sha256 instead.
/opt/boxen/homebrew/Library/Homebrew/extend/pathname.rb:320:in `verify_checksum'

==> script/build
Last 15 lines from /Users/julien/Library/Logs/Homebrew/hub/01.build:
2016-08-22 21:49:10 +0200

script/build

# _/private/tmp/hub-20160822-51203-y0p5wo/hub-2.2.1
/opt/boxen/homebrew/Cellar/go/1.7/libexec/pkg/tool/darwin_amd64/link: -X flag requires argument of the form importpath.name=value

READ THIS: https://git.io/brew-troubleshooting

/opt/boxen/homebrew/Library/Homebrew/utils/github.rb:212:in `raise_api_error': Validation Failed (GitHub::Error)
       	from /opt/boxen/homebrew/Library/Homebrew/utils/github.rb:174:in `open'
       	from /opt/boxen/homebrew/Library/Homebrew/utils/github.rb:219:in `issues_matching'
       	from /opt/boxen/homebrew/Library/Homebrew/utils/github.rb:252:in `issues_for_formula'
       	from /opt/boxen/homebrew/Library/Homebrew/exceptions.rb:312:in `fetch_issues'
       	from /opt/boxen/homebrew/Library/Homebrew/exceptions.rb:308:in `issues'
       	from /opt/boxen/homebrew/Library/Homebrew/exceptions.rb:353:in `dump'
       	from /opt/boxen/homebrew/Library/Homebrew/brew.rb:126:in `rescue in <main>'
       	from /opt/boxen/homebrew/Library/Homebrew/brew.rb:26:in `<main>'
Error: /Stage[main]/Hub/Package[boxen/brews/hub]/ensure: change from 2.2.5 to Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/opt/boxen/homebrew/Library/Taps/boxen/homebrew-brews/hub.rb:6:in `<class:Hub>'
Please report this to the boxen/brews tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/opt/boxen/homebrew/Library/Taps/boxen/homebrew-brews/hub.rb:6:in `<class:Hub>'
Please report this to the boxen/brews tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/opt/boxen/homebrew/Library/Taps/boxen/homebrew-brews/hub.rb:6:in `<class:Hub>'
Please report this to the boxen/brews tap!

2.2.1 failed: Could not update: Execution of 'brew boxen-install boxen/brews/hub' returned 1: Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/opt/boxen/homebrew/Library/Taps/boxen/homebrew-brews/hub.rb:6:in `<class:Hub>'
Please report this to the boxen/brews tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/opt/boxen/homebrew/Library/Taps/boxen/homebrew-brews/hub.rb:6:in `<class:Hub>'
Please report this to the boxen/brews tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/opt/boxen/homebrew/Library/Taps/boxen/homebrew-brews/hub.rb:6:in `<class:Hub>'
Please report this to the boxen/brews tap!

Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
==> Installing hub from boxen/brews
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/opt/boxen/homebrew/Library/Taps/boxen/homebrew-brews/hub.rb:6:in `<class:Hub>'
Please report this to the boxen/brews tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/opt/boxen/homebrew/Library/Taps/boxen/homebrew-brews/hub.rb:6:in `<class:Hub>'
Please report this to the boxen/brews tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/opt/boxen/homebrew/Library/Taps/boxen/homebrew-brews/hub.rb:6:in `<class:Hub>'
Please report this to the boxen/brews tap!

==> Downloading https://github.com/github/hub/archive/v2.2.1.tar.gz
Already downloaded: /opt/boxen/cache/homebrew/hub-2.2.1.tar.gz
Warning: Calling Pathname#sha1 is deprecated!
Use Pathname#sha256 instead.
/opt/boxen/homebrew/Library/Homebrew/extend/pathname.rb:320:in `verify_checksum'

==> script/build
Last 15 lines from /Users/julien/Library/Logs/Homebrew/hub/01.build:
2016-08-22 21:49:10 +0200

script/build

# _/private/tmp/hub-20160822-51203-y0p5wo/hub-2.2.1
/opt/boxen/homebrew/Cellar/go/1.7/libexec/pkg/tool/darwin_amd64/link: -X flag requires argument of the form importpath.name=value

READ THIS: https://git.io/brew-troubleshooting

/opt/boxen/homebrew/Library/Homebrew/utils/github.rb:212:in `raise_api_error': Validation Failed (GitHub::Error)
       	from /opt/boxen/homebrew/Library/Homebrew/utils/github.rb:174:in `open'
       	from /opt/boxen/homebrew/Library/Homebrew/utils/github.rb:219:in `issues_matching'
       	from /opt/boxen/homebrew/Library/Homebrew/utils/github.rb:252:in `issues_for_formula'
       	from /opt/boxen/homebrew/Library/Homebrew/exceptions.rb:312:in `fetch_issues'
       	from /opt/boxen/homebrew/Library/Homebrew/exceptions.rb:308:in `issues'
       	from /opt/boxen/homebrew/Library/Homebrew/exceptions.rb:353:in `dump'
       	from /opt/boxen/homebrew/Library/Homebrew/brew.rb:126:in `rescue in <main>'
       	from /opt/boxen/homebrew/Library/Homebrew/brew.rb:26:in `<main>'
```

**Comment by jacobbednarz** [comment]
It looks like you are running an older version of Boxen (since hub was updated to 2.2.3 and resolved many of those deprecation notices via boxen/puppet-hub#16). Can you try updating to the latest version?

However I have not seen this warning before:

```
# _/private/tmp/hub-20160822-51203-y0p5wo/hub-2.2.1
/opt/boxen/homebrew/Cellar/go/1.7/libexec/pkg/tool/darwin_amd64/link: -X flag requires argument of the form importpath.name=value

READ THIS: https://git.io/brew-troubleshooting

/opt/boxen/homebrew/Library/Homebrew/utils/github.rb:212:in `raise_api_error': Validation Failed (GitHub::Error)
        from /opt/boxen/homebrew/Library/Homebrew/utils/github.rb:174:in `open'
        from /opt/boxen/homebrew/Library/Homebrew/utils/github.rb:219:in `issues_matching'
        from /opt/boxen/homebrew/Library/Homebrew/utils/github.rb:252:in `issues_for_formula'
        from /opt/boxen/homebrew/Library/Homebrew/exceptions.rb:312:in `fetch_issues'
        from /opt/boxen/homebrew/Library/Homebrew/exceptions.rb:308:in `issues'
        from /opt/boxen/homebrew/Library/Homebrew/exceptions.rb:353:in `dump'
        from /opt/boxen/homebrew/Library/Homebrew/brew.rb:126:in `rescue in <main>'
        from /opt/boxen/homebrew/Library/Homebrew/brew.rb:26:in `<main>'
```

Have you tried the troubleshooting link? I also run Go 1.7 locally and don't receive this on El Capitan but I'm not 100% sure this is Boxen related. 

The `
/opt/boxen/homebrew/Library/Homebrew/utils/github.rb:212:in 'raise_api_error': Validation Failed (GitHub::Error)` suggests this is an issue with the connection to GitHub. Once you update `hub` can you try running `boxen --debug`? This will run puppet in verbose mode and give you more of an idea where things are failing and what is happening leading up to the failure.

**Comment by julienlavergne** [comment]
@jacobbednarz Thank you. Bump simply puppet-hub to 1.4.3 fixed the problem.

**Comment by jacobbednarz** [comment]
Awesome news!
