### ISSUE TITLE
Keychain error running boxen through SSH

### ISSUE THREAD

**Issue by also** [boxen/boxen#54]
If I SSH into my Mac, I can't even run `boxen --help`

```
ryans-mac:src ryan$ boxen --help --no-pull
Boxen Keychain Helper: Encountered error code: -25308
Boxen Keychain Helper: Encountered error code: -25308
--> Hey, I need your current GitHub credentials to continue.

GitHub login: |also| 
GitHub password: ********
Boxen Keychain Helper: Encountered error code: -25308
Boxen Keychain Helper: Encountered error code: -25308
/opt/boxen/repo/.bundle/ruby/1.8/gems/boxen-1.0.1/lib/boxen/keychain.rb:54:in `set': Can't save GitHub Password in the keychain. (Boxen::Error)
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/boxen-1.0.1/lib/boxen/keychain.rb:28:in `password='
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/boxen-1.0.1/lib/boxen/config.rb:62:in `save'
	from /opt/boxen/repo/.bundle/ruby/1.8/gems/boxen-1.0.1/lib/boxen/cli.rb:48:in `run'
	from /opt/boxen/bin/boxen:71
ryans-mac:src ryan$
```

Seems like it should at least be able to display the help without trying to save my password.

**Comment by marr** [comment]
@idris did you ever get this sorted out?

**Comment by idris** [comment]
Yeah, I don't have this problem anymore.  Sadly I don't remember what I did to resolve it :(

**Comment by seanknox** [comment]
Closing this since it's working as expected. Feel free to open a PR to update documentation if you think it's useful. Thanks!
